# Generated by Django 3.1.7 on 2021-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
