# Generated by Django 3.1.7 on 2021-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventattendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendees',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
