# Generated by Django 3.1.7 on 2021-04-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210418_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendees',
            name='event',
            field=models.IntegerField(),
        ),
    ]
