# Generated by Django 3.1.7 on 2021-04-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210418_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendees',
            name='event',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventattendees',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
