# Generated by Django 3.1.7 on 2021-04-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210404_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receive_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receive_site',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receive_time',
        ),
    ]
