# Generated by Django 3.1.7 on 2021-04-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_flavour',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_milk',
        ),
    ]
