# Generated by Django 3.1.7 on 2021-03-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210324_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
