# Generated by Django 3.1.7 on 2021-03-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavours',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='loyalty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='milks',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
