# Generated by Django 3.1.7 on 2021-04-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210329_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='milks',
        ),
    ]
