# Generated by Django 3.1.7 on 2021-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210420_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='0', max_length=254),
            preserve_default=False,
        ),
    ]
